<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sage.Active\Sage.Active.csproj" />
    <ProjectReference Include="..\..\src\Sage.Active.AspNetCore\Sage.Active.AspNetCore.csproj" />
  </ItemGroup>

</Project>
