using System.IO;

namespace Sage.Active.Cli
{
    /// <summary>
    /// Generates a starter usage file adapted to the detected project style.
    /// Extension method or standalone helper - never collides with user's existing Program.cs.
    /// </summary>
    public static class CodeScaffolder
    {
        public static string? GetTargetPath(string directory, DetectedProject project)
        {
            if (project.IsFileBasedApp) return null;

            return project.Kind switch
            {
                ProjectFrameworkKind.AspNetCoreWeb => Path.Combine(directory, "Endpoints", "SageActiveEndpoints.cs"),
                ProjectFrameworkKind.WorkerService => Path.Combine(directory, "Workers", "SageSyncWorker.cs"),
                ProjectFrameworkKind.Console or ProjectFrameworkKind.ClassLibrary => Path.Combine(directory, "SageDemo.cs"),
                _ => null,
            };
        }

        public static string? Scaffold(string directory, DetectedProject project)
        {
            var path = GetTargetPath(directory, project);
            if (path == null) return null;

            Directory.CreateDirectory(Path.GetDirectoryName(path)!);

            var code = project.Kind switch
            {
                ProjectFrameworkKind.AspNetCoreWeb => AspNetCoreEndpointsTemplate,
                ProjectFrameworkKind.WorkerService => WorkerServiceTemplate,
                _ => StandaloneDemoTemplate,
            };

            File.WriteAllText(path, code);
            return path;
        }

        private const string AspNetCoreEndpointsTemplate = @"using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Sage.Active;
using Sage.Active.AspNetCore;
using Sage.Active.Models.Entities;

namespace YourApp.Endpoints
{
    /// <summary>
    /// Starter Sage Active API + Webhook endpoints generated by 'sage-active init'.
    /// Wire into Program.cs: app.MapSageActiveEndpoints();
    /// </summary>
    public static class SageActiveEndpoints
    {
        public static IEndpointRouteBuilder MapSageActiveEndpoints(this IEndpointRouteBuilder app)
        {
            // 1. Query Organizations
            app.MapGet(""/sage/organizations"", async (SageActiveClient client) =>
            {
                var orgs = await client.Organizations.GetOrganizationsAsync();
                return Results.Ok(orgs.Nodes);
            });

            // 2. Query Sales Invoices
            app.MapGet(""/sage/invoices"", async (SageActiveClient client) =>
            {
                var invoices = await client.Sales.GetInvoicesAsync();
                return Results.Ok(invoices.Nodes);
            });

            // 3. Receive Sage Event Webhooks
            app.MapSageWebhook(""/sage/webhooks"", async (payload, ctx) =>
            {
                Console.WriteLine($""[Sage Webhook Event]: {payload}"");
                await Task.CompletedTask;
            });

            return app;
        }
    }
}";

        private const string WorkerServiceTemplate = @"using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Sage.Active;

namespace YourApp.Workers
{
    /// <summary>
    /// Background sync worker generated by 'sage-active init'.
    /// Injects SageActiveClient to periodically poll Sage Active.
    /// </summary>
    public class SageSyncWorker : BackgroundService
    {
        private readonly ILogger<SageSyncWorker> _logger;
        private readonly SageActiveClient _client;

        public SageSyncWorker(ILogger<SageSyncWorker> logger, SageActiveClient client)
        {
            _logger = logger;
            _client = client;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation(""Sage Active Sync Worker starting..."");

            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    _logger.LogInformation(""Polling Sage Active for recent sales invoices..."");
                    var invoices = await _client.Sales.GetInvoicesAsync(first: 5, cancellationToken: stoppingToken);
                    _logger.LogInformation(""Found {Count} invoice(s)."", invoices.TotalCount);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(""Polling error: {Message}"", ex.Message);
                }

                await Task.Delay(TimeSpan.FromMinutes(5), stoppingToken);
            }
        }
    }
}";

        private const string StandaloneDemoTemplate = @"using System;
using System.Threading.Tasks;
using Sage.Active;
using Sage.Active.Models;

namespace YourApp
{
    /// <summary>
    /// Starter Sage Active demo helper generated by 'sage-active init'.
    /// </summary>
    public static class SageDemo
    {
        public static async Task RunAsync(SageActiveConfig config)
        {
            var client = new SageActiveClient(config);
            Console.WriteLine($""Connected to Sage Active ({config.Environment})"");

            var orgs = await client.Organizations.GetOrganizationsAsync();
            Console.WriteLine($""Found {orgs.TotalCount} organization(s):"");
            foreach (var org in orgs.Nodes)
            {
                Console.WriteLine($"" - {org.SocialName} ({org.Id})"");
            }
        }
    }
}";
    }
}
